<?php

declare(strict_types=1);

$autoload = __DIR__ . '/../vendor/autoload.php';
if (is_file($autoload)) {
    require $autoload;
} else {
    spl_autoload_register(static function (string $class): void {
        $prefix = 'Maatify\\Seo\\';
        if (!str_starts_with($class, $prefix)) {
            return;
        }

        $path = __DIR__ . '/../src/' . str_replace('\\', '/', substr($class, strlen($prefix))) . '.php';
        if (is_file($path)) {
            require $path;
        }
    });
}

use Maatify\Seo\Web\Robots\DTO\RobotsRuleDTO;
use Maatify\Seo\Web\Robots\DTO\RobotsTxtDTO;
use Maatify\Seo\Web\Robots\RobotsTxtRenderer;

$rule = new RobotsRuleDTO(
    userAgent: '*',
    allow: ['/public/'],
    disallow: ['/admin/', '/private/'],
    crawlDelay: 2, // Non-standard crawler extension; not RFC core or Google-supported.
    comments: ['Crawler access rules for the public site'],
);

$robotsTxt = new RobotsTxtDTO(
    rules: [$rule],
    sitemaps: ['https://example.com/sitemap.xml'],
    comments: ['Generated by the Maatify SEO robots.txt example'],
);

$renderer = new RobotsTxtRenderer();

echo "\n==============================\n";
echo "Robots.txt Output\n";
echo "==============================\n";
echo $renderer->render($robotsTxt);
